name: simple_lan_chat
description: A new Flutter project.
publish_to: none
version: 1.4.2+22

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lan_chat:
    path: packages/lan_chat
  file_picker: ^4.2.0
  path_provider:
  open_file: ^3.2.1

  # Flutterfall
  equatable:
  formz:
  flutter_bloc:

  # UI
  linkwell: ^2.0.6
  dynamic_themes: ^1.1.0
  fluttertoast:
  timeago:
  theme:
    path: packages/chat_theme

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  bloc_test:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.4
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: 'Manrope'
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Bold.ttf
          weight: 700